// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNew1lzGUWl7PyTVeFXJlH54wn-DqKNa4',
    appId: '1:135299879951:web:3a21bf826886372ce5ff7a',
    messagingSenderId: '135299879951',
    projectId: 'businbr-64c1e',
    authDomain: 'businbr-64c1e.firebaseapp.com',
    storageBucket: 'businbr-64c1e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDERgTACWMYzqklhM5thRw1KV1pLzQsZ0k',
    appId: '1:135299879951:android:e4c4046cc58db65ce5ff7a',
    messagingSenderId: '135299879951',
    projectId: 'businbr-64c1e',
    storageBucket: 'businbr-64c1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhAGoQ-pOJoDptaqC-rCAkSpHPZqPFzf4',
    appId: '1:135299879951:ios:ba11e050a84644e5e5ff7a',
    messagingSenderId: '135299879951',
    projectId: 'businbr-64c1e',
    storageBucket: 'businbr-64c1e.firebasestorage.app',
    androidClientId: '135299879951-74ckr64crv8unmpnqe5j87e6lmkjd13e.apps.googleusercontent.com',
    iosClientId: '135299879951-jup4729077o004lqpkq4c2pt1alo72r4.apps.googleusercontent.com',
    iosBundleId: 'com.example.projeAdi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhAGoQ-pOJoDptaqC-rCAkSpHPZqPFzf4',
    appId: '1:135299879951:ios:ba11e050a84644e5e5ff7a',
    messagingSenderId: '135299879951',
    projectId: 'businbr-64c1e',
    storageBucket: 'businbr-64c1e.firebasestorage.app',
    androidClientId: '135299879951-74ckr64crv8unmpnqe5j87e6lmkjd13e.apps.googleusercontent.com',
    iosClientId: '135299879951-jup4729077o004lqpkq4c2pt1alo72r4.apps.googleusercontent.com',
    iosBundleId: 'com.example.projeAdi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNew1lzGUWl7PyTVeFXJlH54wn-DqKNa4',
    appId: '1:135299879951:web:0c611cb043f9cf2de5ff7a',
    messagingSenderId: '135299879951',
    projectId: 'businbr-64c1e',
    authDomain: 'businbr-64c1e.firebaseapp.com',
    storageBucket: 'businbr-64c1e.firebasestorage.app',
  );

}